### ISSUE TITLE
'PyzoEditor' object has no attribute 'removeTrailingWS'

### ISSUE THREAD

**Issue by ysalmon** [pyzo/pyzo#595]
Some user report that they get `'PyzoEditor' object has no attribute 'removeTrailingWS'` when saving a file.
I also experienced it when saving a new file (ie. a  `<tmp1>`).

this seems to have been introduced with https://github.com/pyzo/pyzo/commit/230f4671bf7f2709df47179b18e4aad8df6e1260

Workaround : create an empty .py file (ie with touch), open it in pyzo and then you can save it (including under another name).

A release 4.7.1 should be made when this is fixed ; this is completely blocking for new users and even people who just upgraded.

**Comment by almarklein** [comment]
Thanks for reporting this! A stupid oversight on my part. Now fixed in master. Let's keep this open though for reference...
