### ISSUE TITLE
PySide2-5.11 support (via QtPy)

### ISSUE THREAD

**Issue by stonebig** [pyzo/pyzo#539]
currently failed to make Pyzo work with PySide2-5.11.0a1-5.11.0-cp36-cp36m-win_amd64.whl:

````
C:\WinP\bd36\buQt5\winp64-3.6.x.1\scripts>winpyzo
Un sous-répertoire ou un fichier C:\WinP\bd36\buQt5\winp64-3.6.x.1\settings\.pyzo existe déjà.
Started our command server
Uncaught Python exception: module 'qtpy.QtCore' has no attribute 'QStringListModel'
  File "C:\WinP\bd36\buQt5\winp64-3.6.x.1\python-3.6.5.amd64\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\WinP\bd36\buQt5\winp64-3.6.x.1\python-3.6.5.amd64\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\WinP\bd36\buQt5\winp64-3.6.x.1\python-3.6.5.amd64\scripts\pyzo.exe\__main__.py", line 9, in <module>
    sys.exit(main())
  File "C:\WinP\bd36\buQt5\winp64-3.6.x.1\python-3.6.5.amd64\lib\site-packages\pyzo\__main__.py", line 52, in main
    pyzo.start()
  File "C:\WinP\bd36\buQt5\winp64-3.6.x.1\python-3.6.5.amd64\lib\site-packages\pyzo\__init__.py", line 270, in start
    MainWindow(None, appLocale)
  File "C:\WinP\bd36\buQt5\winp64-3.6.x.1\python-3.6.5.amd64\lib\site-packages\pyzo\core\main.py", line 84, in __init__
    loadFonts()
  File "C:\WinP\bd36\buQt5\winp64-3.6.x.1\python-3.6.5.amd64\lib\site-packages\pyzo\core\main.py", line 520, in loadFonts
    import pyzo.codeeditor  # we need pyzo and codeeditor namespace here
  File "C:\WinP\bd36\buQt5\winp64-3.6.x.1\python-3.6.5.amd64\lib\site-packages\pyzo\codeeditor\__init__.py", line 41, in <module>
    from .extensions.autocompletion import AutoCompletion
  File "C:\WinP\bd36\buQt5\winp64-3.6.x.1\python-3.6.5.amd64\lib\site-packages\pyzo\codeeditor\extensions\autocompletion.py", line 18, in <module>
    class CompletionListModel(QtCore.QStringListModel):


C:\WinP\bd36\buQt5\winp64-3.6.x.1\python-3.6.5.amd64>
````

**Comment by stonebig** [comment]
it works with QtConsole and not with Spyder.

**Comment by stonebig** [comment]
this make pyzo starts: https://github.com/spyder-ide/qtpy/pull/147

**Comment by stonebig** [comment]
at this second level of problem, I don't know if it's  a QtPy, Pyzo, or Pyside2 problem.

**Comment by stonebig** [comment]
ok, pyzo std shell seem to be happy if I add in the path: "%WINPYDIR%\Lib\site-packages\PySide2"

![pyzo_side2_std_shell_ok](https://user-images.githubusercontent.com/4312421/39397135-90dddb40-4afa-11e8-86b9-cdaf85cba545.PNG)

**Comment by stonebig** [comment]
remaining problem: the closing of pyzo in "un-gracefull" : "Python stopped working" message.

**Comment by stonebig** [comment]
fatal error on close bug was already opened in Qt tracker:
https://bugreports.qt.io/projects/PYSIDE/issues/PYSIDE-632?filter=allopenissues


pyside full bug tracker https://bugreports.qt.io/projects/PYSIDE/issues/PYSIDE-632?filter=allopenissues

**Comment by stonebig** [comment]
It's uploaded there with pyzo master https://sourceforge.net/projects/winpython/files/WinPython_3.6/3.6.5.1/alphas/WinPython64-3.6.5.1Ps2a1.exe

**Comment by stonebig** [comment]
you should so add PySide2 in the compatibility comments

**Comment by stonebig** [comment]
I'm not very satisfied with the "tricks" to make pyzo works out-of-the-box, but at least on a sample of 1 pc, it looks ok.

**Comment by stonebig** [comment]
looking  there, we are still 9 month from a reliable PySide2 experience, unless PySide2 improvement process can be speeded-up  https://bugreports.qt.io/secure/ConfigureReport.jspa?projectOrFilterId=project-10840&periodName=daily&daysprevious=299&selectedProjectId=10840&reportKey=com.atlassian.jira.jira-core-reports-plugin%3Aaverageage-report&atl_token=APQ4-KXYT-R7PL-QM80%7Cbb8a94c1f1cb02399efb9b585121db5fbb7f863f%7Clout&Next=Next

**Comment by stonebig** [comment]
" PYSIDE-632 crash on closing" is solved in last https://download.qt.io/snapshots/ci/pyside/5.11/latest/pyside2/PySide2-5.11.0a1.dev1525359714-5.11.0-cp36-cp36m-win_amd64.whl

There is real progress from PySide2
